spring:
  cloud:
    config:
      server:
        git:
          default-label : main
          uri: https://github.com/saadpasta/mission-control-config-server
          clone-on-start: true
          ignoreLocalSshSettings: true
